#ifndef P101_DOCTOR_CONSTANTS_H
#define P101_DOCTOR_CONSTANTS_H

enum
{
    MSG_LEN          = 256,
    MAX_TOOL_ARGS    = 256,
    MODULE_MAP_ARGS  = 7,
    TOOL_ARG_RESERVE = 15,
    UINT_TEXT_LEN    = 32,
    DEFAULT_DIR_MODE = 0755,
    REPORT_FILE_MODE = 0644,
    EXEC_FAILURE     = 127,
    EXIT_FINDINGS    = 1,
    EXIT_TROUBLE     = 2
};

#define DEFAULT_DOCTOR_PREFIX "p101-doctor"
#define DEFAULT_SOURCE_PATH "."
#define DEFAULT_WRAPPER_AUDIT "p101-wrapper-audit"
#define DEFAULT_MODULE_MAP "p101-module-map"
#define DEFAULT_OBSERVE_PATH "p101-observe"
#define DEFAULT_ERROR_WALK_PATH "p101-error-path-walk"
#define DEFAULT_TRACKER_PATH "p101-resource-tracker"
#define DEFAULT_TRACE_PATH "p101-trace"
#define DEFAULT_REPORT_PATH "p101-report"
#define DEFAULT_FAULT_COUNT "16"

#define RESOURCE_LOG_ENV "P101_RESOURCE_LOG"
#define CALL_LOG_ENV "P101_CALL_LOG"
#define CALL_LOG_ARGS_ENV "P101_CALL_LOG_ARGS"
#define CALL_LOG_RESULT_ENV "P101_CALL_LOG_RESULT"
#define FAULT_CALL_ENV "P101_FAULT_CALL"
#define FAULT_ERRNO_ENV "P101_FAULT_ERRNO"
#define FAULT_NAME_ENV "P101_FAULT_NAME"
#define FAULT_LOG_ENV "P101_FAULT_LOG"

#endif    // P101_DOCTOR_CONSTANTS_H
